#!/bin/bash

GIT_ROOT="$(git rev-parse --show-toplevel)"
LINT_VERSION="v1.50.1"
LINT_BIN="$GIT_ROOT/.golangci-lint"

set -e

if [ ! -f "$LINT_BIN" ]; then
    echo "Downloading dependencies (golangci-lint)..."
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GIT_ROOT" "$LINT_VERSION"
    mv "$GIT_ROOT/golangci-lint" "$LINT_BIN"
fi

echo "Running linter (golangci-lint)..."
"$LINT_BIN" run --fix
